CREATE SCHEMA DISCOVERYSYSTEM;

--Create tables here
CREATE TABLE DISCOVERYSYSTEM.ACCOUNT_TYPE( ACCOUNT_TYPE_ID BIGINT NOT NULL PRIMARY KEY, MNEMONIC VARCHAR(20) NOT NULL, ACCOUNT_TYPE_NAME VARCHAR(50) NOT NULL, CREATION_DATE DATE);

CREATE TABLE DISCOVERYSYSTEM.USER_ACCOUNT( USER_ACCOUNT_ID BIGINT NOT NULL PRIMARY KEY, MEMBER_ID BIGINT NOT NULL, ACCOUNT_TYPE_ID BIGINT NOT NULL, ACCOUNT_BALANCE INT NOT NULL DEFAULT ); CREATION_DATE DATE);

CREATE TABLE DISCOVERYSYSTEM.ACCOUNT_TX( TX_ID BIGINT NOT NULL PRIMARY KEY, ACCOUNT_TYPE_ID BIGINT NOT NULL, MEMBER_ID BIGINT NOT NULL, AMOUNT INT NOT NULL, TX_DATE TIMESTAMP NOT NULL);

--Add constraints here
ALTER TABLE DISCOVERYSYSTEM.USER_ACCOUNT ADD CONSTRAINT FK_USER_ACCOUNT_TYPE FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE(ACCOUNT_TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DISCOVERYSYSTEM.ACCOUNT_TX ADD CONSTRAINT FK_ACCOUNT_TX_ACCOUNT_TYPE FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE(ACCOUNT_TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

--CREATE SEQUENCES HERE
CREATE SEQUENCES DISCOVERYSYSTEM.SEQ_TX_ID BEGIN AT 100000000000000000


